### ISSUE TITLE
bug: Home Page isnt displaying images correctly in Firefox 

### ISSUE THREAD

**Issue by varundeepsaini** [varundeepsaini/AlgoVis#1]
![image](https://github.com/varundeepsaini/AlgoVis/assets/140642437/e0822c49-ba55-4de4-977c-5e992e680bbf)
How it is supposed to look

![image](https://github.com/varundeepsaini/AlgoVis/assets/140642437/9a3b8b3e-48ef-4eca-b0b1-c98f021eec00)
How it is looking

**Comment by fivecctv117** [comment]
Hi @varundeepsaini Can I work on this issue?
